<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>KKY_FamilyBrowser_RevitHost_2025</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="KKY.FamilyBrowser.DashboardAssets.family-browser-shell.css" />
    <None Remove="KKY.FamilyBrowser.DashboardAssets.family-browser-shell.js" />
    <EmbeddedResource Include="KKY.FamilyBrowser.DashboardAssets.family-browser-shell.css" LogicalName="KKY.FamilyBrowser.DashboardAssets.family-browser-shell.css" />
    <EmbeddedResource Include="KKY.FamilyBrowser.DashboardAssets.family-browser-shell.js" LogicalName="KKY.FamilyBrowser.DashboardAssets.family-browser-shell.js" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="RevitAPIUI">
      <HintPath>..\Compile\2025addin\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPI">
      <HintPath>..\Compile\2025addin\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
