export const EVENT_NAMES = Object.freeze({
    UI: Object.freeze({
        PING: 'ui:ping',
        QUERY_TOPMOST: 'ui:query-topmost',
        SET_TOPMOST: 'ui:set-topmost',
        TOGGLE_TOPMOST: 'ui:toggle-topmost',
    }),
    HOST: Object.freeze({
        CONNECTED: 'host:connected',
        PONG: 'host:pong',
        TOPMOST: 'host:topmost',
        DOC_CHANGED: 'host:doc-changed',
        DOC_LIST: 'host:doc-list',
        ERROR: 'host:error',
        WARN: 'host:warn',
        INFO: 'host:info',
        LOG: 'host:log',
    }),
    FEATURE: Object.freeze({
        UI: Object.freeze({
            DUP_RUN: 'dup:run',
            DUPLICATE_EXPORT: 'duplicate:export',
            DUPLICATE_DELETE: 'duplicate:delete',
            DUPLICATE_RESTORE: 'duplicate:restore',
            DUPLICATE_SELECT: 'duplicate:select',

            CONNECTOR_RUN: 'connector:run',
            CONNECTOR_SAVE_EXCEL: 'connector:save-excel',

            EXPORT_BROWSE_FOLDER: 'export:browse-folder',
            EXPORT_ADD_RVT_FILES: 'export:add-rvt-files',
            EXPORT_PREVIEW: 'export:preview',
            EXPORT_SAVE_EXCEL: 'export:save-excel',

            PARAMPROP_RUN: 'paramprop:run',
            SHAREDPARAM_RUN: 'sharedparam:run',
            SHAREDPARAM_LIST: 'sharedparam:list',
            SHAREDPARAM_STATUS: 'sharedparam:status',
            SHAREDPARAM_EXPORT_EXCEL: 'sharedparam:export-excel',
            PARAMPROP_LIST: 'paramprop:list',
            PARAMPROP_STATUS: 'paramprop:status',
            PARAMPROP_EXPORT_EXCEL: 'paramprop:export-excel',
            SHAREDPARAM_EXPORT: 'sharedparam:export',

            SHAREDPARAMBATCH_INIT: 'sharedparambatch:init',
            SHAREDPARAMBATCH_BROWSE_RVTS: 'sharedparambatch:browse-rvts',
            SHAREDPARAMBATCH_BROWSE_FOLDER: 'sharedparambatch:browse-folder',
            SHAREDPARAMBATCH_RUN: 'sharedparambatch:run',
            SHAREDPARAMBATCH_EXPORT_EXCEL: 'sharedparambatch:export-excel',
            SHAREDPARAMBATCH_OPEN_FOLDER: 'sharedparambatch:open-folder',

            EXCEL_OPEN: 'excel:open',

            SEGMENTPMS_RVT_PICK_FILES: 'segmentpms:rvt-pick-files',
            SEGMENTPMS_RVT_PICK_FOLDER: 'segmentpms:rvt-pick-folder',
            SEGMENTPMS_EXTRACT: 'segmentpms:extract',
            SEGMENTPMS_LOAD_EXTRACT: 'segmentpms:load-extract',
            SEGMENTPMS_SAVE_EXTRACT: 'segmentpms:save-extract',
            SEGMENTPMS_REGISTER_PMS: 'segmentpms:register-pms',
            SEGMENTPMS_PMS_TEMPLATE: 'segmentpms:pms-template',
            SEGMENTPMS_PREPARE_MAPPING: 'segmentpms:prepare-mapping',
            SEGMENTPMS_RUN: 'segmentpms:run',
            SEGMENTPMS_SAVE_RESULT: 'segmentpms:save-result',

            GUID_ADD_FILES: 'guid:add-files',
            GUID_RUN: 'guid:run',
            GUID_EXPORT: 'guid:export',
            GUID_REQUEST_FAMILY_DETAIL: 'guid:request-family-detail',

            FAMILYLINK_INIT: 'familylink:init',
            FAMILYLINK_PICK_RVTS: 'familylink:pick-rvts',
            FAMILYLINK_RUN: 'familylink:run',
            FAMILYLINK_EXPORT: 'familylink:export',

            HUB_PICK_RVT: 'hub:pick-rvt',
            HUB_MULTI_RUN: 'hub:multi-run',
            HUB_MULTI_EXPORT: 'hub:multi-export',
            HUB_MULTI_CLEAR: 'hub:multi-clear',

            COMMONOPTIONS_GET: 'commonoptions:get',
            COMMONOPTIONS_SAVE: 'commonoptions:save',
        }),
        HOST: Object.freeze({
            DUP_LIST: 'dup:list',
            DUP_EXPORTED: 'dup:exported',
            CONNECTOR_DONE: 'connector:done',
            EXPORT_PREVIEWED: 'export:previewed',
            EXPORT_SAVED: 'export:saved',
            PARAMPROP_DONE: 'paramprop:done',
            PARAMPROP_REPORT: 'paramprop:report',
            FAMILYLINK_SHAREDPARAMS: 'familylink:sharedparams',
            FAMILYLINK_RVTS_PICKED: 'familylink:rvts-picked',
            FAMILYLINK_PROGRESS: 'familylink:progress',
            FAMILYLINK_RESULT: 'familylink:result',
            FAMILYLINK_EXPORTED: 'familylink:exported',
        }),
    }),
});